# Numpy Practice Session
## 1-D Array

In [ ]:
# pip install numpy # already install in jupyter

### Creating an array

In [1]:
import numpy as np
a= np.array([2,3,7,8,0])
a

array([2, 3, 7, 8, 0])

In [2]:
# ndarray is a class of Numpy library which represents matrices and vectors. 
# vectors are sigle dimentional arrays while matrices refers to two dimensional arrays.
# Dimensions are called axis.
type(a) 

numpy.ndarray

In [3]:
# Length of the array
len(a)

5

In [4]:
# indexing in the the array
a[1] 

3

In [5]:
# indexing all in the the array
a[0:] 

array([2, 3, 7, 8, 0])

In [6]:
#sorting array
np.sort(a)

array([0, 2, 3, 7, 8])

In [7]:
# dimension of the  array
np.ndim(a)

1

In [121]:
# to find unique elements in the array
np.unique(a)

array([ 2,  3,  6,  7, 45])

In [9]:
np.ones(3)

array([1., 1., 1.])

In [19]:
# default data type is floating point (np.float64), you can explicitly specify
np.ones(3, dtype=np.int64)

array([1, 1, 1], dtype=int64)

In [119]:
# generate arrays of zeros 
np.zeros(4)

array([0., 0., 0., 0.])

In [118]:
# generate arrays of random numbers
rng = np.random.default_rng()
rng.random(3)

array([0.22812557, 0.63642781, 0.29747132])

In [11]:
# array with a range of elements
np.arange(5)

array([0, 1, 2, 3, 4])

In [12]:
# defined range of elements where last element is exclusive. reason will be 
np.arange(5,10) 

array([5, 6, 7, 8, 9])

In [13]:
# values that are spaced linearly in a specified interval
np.linspace(1,6, num=3)

array([1. , 3.5, 6. ])

In [28]:
# function empty creates an array whose initial content is random and depends on the state of the memory
b=np.empty(3)
b

array([1. , 3.5, 6. ])

In [32]:
fruit=np.array(["mango","bananna","apple"])
fruit

array(['mango', 'bananna', 'apple'], dtype='<U7')

In [35]:
price=np.array([50,35,45])
price

array([50, 35, 45])

### Array Functions

In [38]:
price.mean()

43.333333333333336

In [39]:
x=np.array([34,5,68,30,6])
y=np.array([5,7,8,9,34,5,4])
x,y

(array([34,  5, 68, 30,  6]), array([ 5,  7,  8,  9, 34,  5,  4]))

In [44]:
z=np.concatenate((x,y))
z

array([34,  5, 68, 30,  6,  5,  7,  8,  9, 34,  5,  4])

In [43]:
np.sort(z)

array([ 4,  5,  5,  5,  6,  7,  8,  9, 30, 34, 34, 68])

## 2-D Array

In [8]:
a= np.array([[2,3,7,8,0], [3,45,6,7,8,]])
a

array([[ 2,  3,  7,  8,  0],
       [ 3, 45,  6,  7,  8]])

In [21]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
# default data type is floating point (np.float64), you can explicitly specify
np.ones((3,4), dtype=np.int64)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int64)

In [23]:
# Creat Array of zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
# Creat empty 2 -D Array 
b=np.empty((3,4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
import numpy as np
a= np.array([5,5,])
a

array([5, 5])

In [16]:
type(a)

numpy.ndarray

In [17]:
#list of lists
b= np.array([[5,5,5],[5,5,5],[5,5,5]])
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [49]:
# concatenate 2-D arrays 
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
x,y
z=np.concatenate((x,y))
z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [112]:
a= np.array([[2,3,7], [3,45,6,]])
b= np.array([[5,6,7,], [3,45,8,]])
a,b

(array([[ 2,  3,  7],
        [ 3, 45,  6]]),
 array([[ 5,  6,  7],
        [ 3, 45,  8]]))

In [57]:
# Concatenate 2 arrays along axis 0 , size must be matching of both array
c=np.concatenate((a,b), axis=0)
c

array([[ 2,  3,  7],
       [ 3, 45,  6],
       [ 5,  6,  7],
       [ 3, 45,  8]])

In [58]:
# Concatenate along axis 0 
c=np.concatenate((a,b), axis=1)
c

array([[ 2,  3,  7,  5,  6,  7],
       [ 3, 45,  6,  3, 45,  8]])

In [113]:
# Vertical and horizontal stacking (all the input arrays must have same number of dimensions)
np.vstack((a, b)), np.hstack((a, b)) 

(array([[ 2,  3,  7],
        [ 3, 45,  6],
        [ 5,  6,  7],
        [ 3, 45,  8]]),
 array([[ 2,  3,  7,  5,  6,  7],
        [ 3, 45,  6,  3, 45,  8]]))

## 3-D Array

In [123]:
a=np.array([[[ 2,  3,  7],
           [ 3, 45,  8]],
           
           [[ 3, 45,  6],
            [5,  6,  7]],
           
             [[5, 5, 5],
             [5, 5, 5]]])
a,a.ndim

array([[[ 2,  3,  7],
        [ 3, 45,  8]],

       [[ 3, 45,  6],
        [ 5,  6,  7]],

       [[ 5,  5,  5],
        [ 5,  5,  5]]])

In [124]:
# to transpose arrays rows to column
a.T

array([[[ 2,  3,  5],
        [ 3,  5,  5]],

       [[ 3, 45,  5],
        [45,  6,  5]],

       [[ 7,  6,  5],
        [ 8,  7,  5]]])

In [65]:
b=np.array([[[ 7,  3,  89],
        [ 34, 4,  18]],

       [[ 23, 5,  0],
        [ 5,  6,  7]],

       [[ 4,  4,  5],
        [ 5,  5,  6]]])
b

array([[[ 7,  3, 89],
        [34,  4, 18]],

       [[23,  5,  0],
        [ 5,  6,  7]],

       [[ 4,  4,  5],
        [ 5,  5,  6]]])

In [66]:
#making and reshaping array
np.arange(24).reshape(2,3,4) # size defined in reshape should be equal to size of array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [114]:
a.size, a.shape

(6, (2, 3))

### Different methods in Arrays

In [79]:
a=np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [83]:
# a is the array to be reshaped with the newshape which is the new shape you want. The shape should be compatible with the original shape.
np.reshape(a, newshape=(3,3) , order="C")

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [96]:
# Using np.newaxis will increase the dimensions of your array by one dimension when used once.
a=np.arange(9)
a,a.shape,a.ndim

(array([0, 1, 2, 3, 4, 5, 6, 7, 8]), (9,), 1)

In [88]:
# 1-D to 2-D array conversion
a1 = a[np.newaxis, :]
a1,a1.shape,a1.ndim

(1, 9)

In [95]:
# 2-D to 3-D array conversion
a2 = a1[np.newaxis, :]
a2, a2.shape,a2.ndim

(array([[[0, 1, 2, 3, 4, 5, 6, 7, 8]]]), (1, 1, 9), 3)

In [125]:
# conversion of array to 1 D 
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x,x.flatten(), x.ravel() 
# difference of ravel() is that any changes after 1D conversion effects the original/parent array

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]))

In [108]:
# Indexing and slicing with arrays
a[3:6], a[-2:] # forward and reverse slicing 

(array([3, 4, 5]), array([7, 8]))

In [109]:
#conditional indexing
a[a[(a > 2) & (a < 11)]] 

array([3, 4, 5, 6, 7, 8])

In [101]:
# math functions with arrays
a.sum(), a.mean(), a.min(),a.max()

(36, 4.0, 0, 8)

In [ ]:
# convert a 1D array with either a row vector or a column vector
row_vector = a[np.newaxis, :]
col_vector = a[:, np.newaxis]
row_vector, col_vector

In [110]:
# inserting a new axis 
np.expand_dims(a, axis=1), np.expand_dims(a, axis=0)

(array([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8]]),
 array([[0, 1, 2, 3, 4, 5, 6, 7, 8]]))